sonar.projectKey=asmaasma13154-sketch_hotel-app
sonar.organization=asmaasma13154-sketch
sonar.projectName=Hotel App Laravel
sonar.sources=app,routes,database
sonar.tests=tests
sonar.php.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**
sonar.sourceEncoding=UTF-8
